### ISSUE TITLE
Add it to awesome-mcp-servers

### ISSUE THREAD

**Issue by punkpeye** [ktanaka101/mcp-server-duckdb#1]
Considering adding your tool to:

https://github.com/punkpeye/awesome-mcp-servers/

You can create a PR directly from README.md.

Just a suggestion!

**Comment by ktanaka101** [comment]
Thank you for the suggestion! That's a great idea to make the project more discoverable.
I'll create a PR to add it to the awesome-mcp-servers list right away. 😊

**Comment by ktanaka101** [comment]
Done! Created PR at https://github.com/punkpeye/awesome-mcp-servers/pull/8 to add it to the list. Thank you for the suggestion!
